### ISSUE TITLE
RETHINK_PATH Not Found

### ISSUE THREAD

**Issue by jpasilan** [vFense/vFense#201]
I have tried another fresh install of the vFense server but I cannot continue because an error (shown below) occurs when I try to run initialize_vFense.py.

```bash
starting listener
listener started
Im about to connect to the listener
localhost 9004
I'm connected to the listener
I'm sending the new config file over
new config sent
shutting down listener
listener is down
Rethink is not Running
Traceback (most recent call last):
  File "/opt/TopPatch/tp/src/scripts/initialize_vFense.py", line 338, in <module>
    db_clean, db_msg = clean_database(connected)
  File "/opt/TopPatch/tp/src/scripts/initialize_vFense.py", line 308, in clean_database
    os.chdir(RETHINK_PATH)
OSError: [Errno 2] No such file or directory: '/usr/share/rethinkdb'
```
I've gone as far as creating that directory manually and vFense did successfully install. However, I cannot add an agent nor login to the WebUI because I get an "Invalid username or password" error. I also get this error a few minutes after starting the vFense daemon.

```bash
Traceback (most recent call last):
  File "src/scheduler/rvscheduler.py", line 17, in <module>
    get_supported_apps()
  File "/usr/local/lib/python2.7/dist-packages/vFense/plugins/patching/apps/supported_apps/syncer.py", line 366, in get_supported_apps
    os.path.join(BASE_URL, GET_SUPPORTED_UPDATES)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 68, in get
    return request('get', url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 464, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', error(110, 'Connection timed out'))
```

The install was done on a DigitalOcean instance using the Ubuntu 12.04.5 x64 image. I was able to successfully vFense server on a similar instance the previous week.

I hope that someone can help resolve this issue. Thanks!

**Comment by linuxdynasty** [comment]
Looks like you did not run the initialize_vfense.py script as that script should have created everything for you. Though Rethinkdb 2.0 just came out, I need to make sure that vFense is compatible with that version of RethinkDB

**Comment by jpasilan** [comment]
> Looks like you did not run the initialize_vfense.py script as that script should have created everything for you.

The first error is actually the result of running initialize_vFense.py

> Though Rethinkdb 2.0 just came out, I need to make sure that vFense is compatible with that version of RethinkDB

This is what I'm thinking too as everything was fine prior to the RethinkDB update.

**Comment by jpasilan** [comment]
Any update on this? Thanks!

**Comment by linuxdynasty** [comment]
The quickest thing to do is to downgrade to the previous RethinkDB. I will see if I have time this week to update vFense so that it is compatible with the latest RethinkDB.

**Comment by deniszh** [comment]
Faced same issue. It seems current vFence is not compatible with RethinkDB 2.x
So, proper fix is downgrade RethinkDB and it's pyhon driver to 1.x.
For Ubuntu 12.04:
```apt-get install rethinkdb=1.16.3~0precise
pip install -Iv rethinkdb==1.16.0-4``
and restart vFence afterwards.

**Comment by linuxdynasty** [comment]
I'm almost done getting vFense RethinkDB 2.0 compatible in the pre-0.8.1-dev branch. Still testing...

**Comment by diogoleal** [comment]
I changed ```RETHINK_PATH``` for ```/usr/bin/rethinkdb_data/``` and it worked.
I'm using Ubuntu 14.04.

**Comment by ovenmitt** [comment]
Has this been fixed? Both the newer versions of RethinkDB and 1.x are not working; they're giving the same error (OSError: [Errno 2] No such file or directory: '/usr/share/rethinkdb')
