### ISSUE TITLE
Running vFense in a company 

### ISSUE THREAD

**Issue by Matesack** [vFense/vFense#202]
Hello,

 I'm writing you because we are looking for some tool as vFense in our company (cca 60 PC/notebooks) and vFense looks very very good to meet our requirements.

 Saidly, we were not able to make it fully work, so I want to ask you for some help or informations how to. In our company we are using many platforms (Win 7, Mac OS X, Linux - Ubuntu, Fedora) and we need to managed them all in one tool.

 We install vFense on Ubuntu 12.0.4 server , then we try to install agents on Fedora, Elementary OS, Windows and Mac OS X and we found many issues.

Main issues:
 - what branches of the software we should use? Which are the newest?
 - which parts we should use? Now we are trying to use:
   - vFense, vFenseAgent-win, vFense-UI and vFenseAgent-nix
- When do you think will be available the stable version of vFense.

Questions:
Windows - we built project in Visual studio and run Agent.Console.exe and it ends with message:
"Loading console
 Starting up TopPatch Windows agent
 Retrieving Ip/Hostname from config file
 Found ip address: 10.1.0.218 (and nothing else)"
 - this notebook will not appear in the Agent menu in vFense

Linux - 
 Fedora - agent runs on Fedora quite well, but it still have some problem with JSON format
  error output - 
  "DEBUG : 05/18/2015 02:26:18 PM : Sending message to: https://omnipotentus:443/rvl/v2/4cba1ac5-a286-4f8e-9752-ac8efcfbd7f4/core/stats/monitordata
DEBUG : 05/18/2015 02:26:18 PM : Message being sent: {"operation_id": "a765e4d1-916c-4e9c-845f-035adf3f7bc7-agent", "operation": "monitor_data", "agent_id": "4cba1ac5-a286-4f8e-9752-ac8efcfbd7f4", "error": "'total'"}
DEBUG : 05/18/2015 02:26:18 PM : Status code: 500
DEBUG : 05/20/2015 09:24:37 AM : Server text: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1413, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/usr/lib/python2.7/vFense/core/receiver/decorators.py", line 119, in wrapper
    self.write(json.dumps(results.to_dict_non_null(), indent=4))
  File "/usr/lib/python2.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 203, in encode
    chunks = list(chunks)
  File "/usr/lib/python2.7/json/encoder.py", line 428, in _iterencode
    for chunk in _iterencode_dict(o, _current_indent_level):
  File "/usr/lib/python2.7/json/encoder.py", line 402, in _iterencode_dict
    for chunk in chunks:
  File "/usr/lib/python2.7/json/encoder.py", line 436, in _iterencode
    o = _default(o)
  File "/usr/lib/python2.7/json/encoder.py", line 178, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: TypeError("TypeError('expected string or buffer',) is not JSON serializable",) is not JSON serializable
 
ERROR : 05/20/2015 09:24:37 AM : {}
ERROR : 05/20/2015 09:24:37 AM : Unable to read data from server. Invalid JSON?
ERROR : 05/20/2015 09:24:37 AM : Exception: No JSON object could be decoded
DEBUG : 05/20/2015 09:24:37 AM : Traceback (most recent call last):
  File "/opt/vFense/agent/src/net/netmanager.py", line 174, in send_message
    received_data = response.json()
  File "/opt/vFense/agent/deps/requests/models.py", line 651, in json
    return json.loads(self.text or self.content, **kwargs)
  File "/opt/vFense/agent/deps/rpm6/Python-2.7.5/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/opt/vFense/agent/deps/rpm6/Python-2.7.5/lib/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/vFense/agent/deps/rpm6/Python-2.7.5/lib/python2.7/json/decoder.py", line 383, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

Mac OS X - agent is not sending the monitoring data, and the list of updates of applications is not complete and after the updates are done, the list in the vFense still keeps the applications as non-updated.

I'm really sorry, but we really like yours vFense and we want to use it, but the deadlines in work pushing us and the time for the implementation is getting shorter. 

Thanks for any help and have a nice day,

Matesack

**Comment by linuxdynasty** [comment]
My apologies for not getting back to you sooner. The issue here is that the current version of vFense in the current branch is not RethinkDB 2.0 compatible. If you downgrade to the previous release of RethinkDB this will no longer be an issue. I am working hard on getting vFense RethinkDB 2.0 compatible.
