### ISSUE TITLE
Initialize vFense Ubuntu 12.4 failed

### ISSUE THREAD

**Issue by Nezsya** [vFense/vFense#203]
Hello,
I am getting the following two errors, after sudo python /opt/TopPatch/tp/src/scripts/initialize_vFense.py --dnsname...
System: 
- Ubuntu 12.04 via oracle vm
- 9gb ram
- ssd 30gb
- downgraded to rethinkdb  1.16.0-4

Errors:

/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning

Done Updating CVE's...
Updating Microsoft Security Bulletin Ids...
Traceback (most recent call last):
  File "/opt/TopPatch/tp/src/scripts/initialize_vFense.py", line 340, in <module>
    db_initialized, msg = initialize_db()
  File "/opt/TopPatch/tp/src/scripts/initialize_vFense.py", line 286, in initialize_db
    parse_bulletin_and_updatedb()
  File "/usr/local/lib/python2.7/dist-packages/vFense/plugins/vuln/windows/parser.py", line 117, in parse_bulletin_and_updatedb
    bulletin_data = parse_spread_sheet(xls_file)
  File "/usr/local/lib/python2.7/dist-packages/vFense/plugins/vuln/windows/parser.py", line 34, in parse_spread_sheet
    workbook = open_workbook(bulletin_file)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/__init__.py", line 394, in open_workbook
    f = open(filename, "rb")
TypeError: coercing to Unicode: need string or buffer, NoneType found

log file msg:
2015-06-13 14:15:36 - cve - INFO - finished cve/nvd update process
2015-06-13 14:15:36 - cve - INFO - starting microsoft security bulletin update process
2015-06-13 14:15:42 - cve - ERROR - failed to retrieve XLSX url from http://www.microsoft.com/en-us/download/confirmation.aspx?id=36982: count = 1
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/vFense/plugins/vuln/windows/downloader.py", line 68, in get_msft_bulletin_url
    main_url.content

Thx in advance
nezy

**Comment by sleavitt** [comment]
I am seeing this issue as well.

**Comment by sleavitt** [comment]
Apparently, Microsoft has changed the format of the spreadsheet from .xlsx to .xls for the Microsoft Security Bulletin, as near as I can tell. Changing the regular expression to match either .xls or .xlsx allowed the init process to work, though I'm not far enough along to determine if it's the only thing that needs doing yet.

```diff
diff --git a/tp/src/plugins/vuln/windows/downloader.py b/tp/src/plugins/vuln/windows/downloader.py
index 46d1696..c21657f 100644
--- a/tp/src/plugins/vuln/windows/downloader.py
+++ b/tp/src/plugins/vuln/windows/downloader.py
@@ -64,7 +64,7 @@ def get_msft_bulletin_url(count=0):

         if main_url.status_code == 200:
             xls_url = re.search(
-                '"(http://download.microsoft.com/download.*.xlsx)",',
+                '"(http://download.microsoft.com/download.*.xlsx?)",',
                 main_url.content
             ).group(1)
```

**Comment by linuxdynasty** [comment]
@sleavitt, thank you for catching that. I accepted @cz-guardian PR, but than I modified it as per your suggestion, which matches both, just incase they feel like changing it again.
