### ISSUE TITLE
Uncompressed CVE XML files are no longer available from nvd.nist.gov

### ISSUE THREAD

**Issue by shawndjw** [vFense/vFense#208]
As stated on https://nvd.nist.gov/Data-Feeds/datafeedinfo

Effective October 16, 2015 the XML data feeds will no longer be available for download in an uncompressed format.

http://nvd.nist.gov/download/nvdcve-2015.xml redirects to https://nvd.nist.gov/Data-Feeds/datafeedinfo

This breaks the vFense initialization and I assume subsequent CVE updates.

Here's the error:

<pre>
Updating CVE's...
Traceback (most recent call last):
  File "/opt/TopPatch/tp/src/scripts/initialize_vFense.py", line 340, in <module>
    db_initialized, msg = initialize_db()
  File "/opt/TopPatch/tp/src/scripts/initialize_vFense.py", line 283, in initialize_db
    load_up_all_xml_into_db()
  File "/usr/lib/python2.7/site-packages/vFense/plugins/vuln/cve/parser.py", line 366, in load_up_all_xml_into_db
    parse_cve_and_udpatedb(False, nvd_files)
  File "/usr/lib/python2.7/site-packages/vFense/plugins/vuln/cve/parser.py", line 314, in parse_cve_and_udpatedb
    for event, entry in etree.iterparse(nvd_file, events=['start', 'end']):
  File "iterparse.pxi", line 487, in lxml.etree.iterparse.__next__ (src/lxml/lxml.etree.c:114535)
  File "iterparse.pxi", line 540, in lxml.etree.iterparse._read_more_events (src/lxml/lxml.etree.c:115115)
  File "parser.pxi", line 616, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:84811)
lxml.etree.XMLSyntaxError: EntityRef: expecting ';', line 9, column 109</pre>

**Comment by shawndjw** [comment]
I was able to implement the following workaround.

<pre>cd /opt/TopPatch/tp/src/plugins/vuln/cve/data/xml
for i in `seq 2002 2015`
  do sudo wget https://nvd.nist.gov/download/nvdcve-${i}.xml.gz
  sudo gzip -d nvdcve-${i}.xml
done</pre>
