### ISSUE TITLE
OSError: [Errno 2] No such file or directory: '/usr/share/rethinkdb'

### ISSUE THREAD

**Issue by memass** [vFense/vFense#222]
OSError: [Errno 2] No such file or directory: '/usr/share/rethinkdb'

I am getting this error when i am using below command
 sudo python /opt/TopPatch/tp/src/scripts/initialize_vFense.py --dnsname=admin --password=Admin@123

& the output like this after entering the command
starting listener
listener started
Im about to connect to the listener
localhost 9004
I'm connected to the listener
I'm sending the new config file over
new config sent
shutting down listener
listener is down
Rethink is Running
Traceback (most recent call last):
  File "/opt/TopPatch/tp/src/scripts/initialize_vFense.py", line 338, in <module>
    db_clean, db_msg = clean_database(connected)
  File "/opt/TopPatch/tp/src/scripts/initialize_vFense.py", line 308, in clean_database
    os.chdir(RETHINK_PATH)
OSError: [Errno 2] No such file or directory: '/usr/share/rethinkdb'

**Comment by kentbrorsson** [comment]
I have the same problem. Anyone who know what is wrong?

**Comment by theangryangel** [comment]
I'd suggest your RethinkDB version is too new - see https://github.com/vFense/vFense/issues/201
